#!/bin/bash

curr=$(pwd)
cd $(cat ~/.notes/path)
cur=$(pwd)

if [[ $1 == "--date" ]]
then
now=$(./src/handle_date.py $2)
if [[ $now == "Not Date!" ]]
then
echo $now
exit
fi
password=$(./src/make_edit)
cd diarys
elif [[ $1 == "--make-list" ]]
then
$(./src/make_list $2 $3)
now="list"
elif [[ $1 == "--protect" ]]
then
sudo chattr +i -R diarys
exit
elif [[ $1 == "--unprotect" ]]
then
sudo chattr -iR diarys
exit
elif [[ $1 == "--set-mode" ]]
then
cat << EOF > src/mode
$2
EOF
exit
elif [[ $1 == "--get-mode" ]]
then
cat src/mode
exit
elif [[ $1 == "--update-path" ]]
then
cat << EOF > ~/.notes/path
$2
EOF
exit
elif [[ $1 == "--get-path" ]]
then
cat ~/.notes/path
exit
elif [[ $1 == "--get-list" ]]
then
./src/make_list $2 $3 --get-list
exit
elif [[ $1 == "--remove-list" ]]
then
ls list > /dev/null 2>&1
if [[ $? -ne 0 ]]
then
exit
fi
rm list
exit
elif [[ $1 == "--help" ]]
then
cat src/help
exit
elif [[ $1 == "--encrypt" ]]
then
shift 1
./src/make_edit
./src/encrypt_and_decrypt -e $@
exit
elif [[ $1 == "--decrypt" ]]
then
shift 1
./src/make_edit
./src/encrypt_and_decrypt -d $@
exit
elif [[ $1 == "--make-res" ]]
then
if [[ $2 == "--date" ]]
then
now=$(./src/handle_date.py $3)
if [[ $now == "Not Date!" ]]
then
echo $now
exit
fi
shift 3
else
now=$(date +'%Y%m%d%w')
shift 1
fi
./src/make_res -m $now $curr $@
exit
elif [[ $1 == "--get-res" ]]
then
if [[ $2 == "--date" ]]
then
now=$(./src/handle_date.py $3)
if [[ $now == "Not Date!" ]]
then
echo $now
exit
fi
shift 3
else
now=$(date +'%Y%m%d%w')
shift 1
fi
./src/make_res -g $now $@
exit
else
now=$(date +'%Y%m%d%w')
password=$(./src/make_edit)
cd diarys
fi

ls $now > /dev/null 2>&1
if [[ $? -ne 0 ]]
then
cat << EOF > $now
$(./../src/handle_date.py $now '%w %m%d %Y')
EOF
fi

nano -lmiS$ -T 2 $now

cd $cur
./src/make_edit --$(cat src/mode) $password
